version: '3'
services:
  db:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: 'reserve'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql_volume:/var/lib/mysql
  nginx:
    build: ./nginx/.
    ports:
      - '8000:80'
    depends_on: # 追加
      - app
      - db
    volumes:
      - ./php:/var/www/html
  app:
    build: ./php
    volumes:
      - ./php:/var/www/html
    ports:
      - 5173:5173
    depends_on:
      - db
